version: '2'

networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
        - POSTGRESQL_USERNAME=ze
        - POSTGRESQL_PASSWORD=zeManel
        - POSTGRESQL_DATABASE=postgresql
    networks:
      - app-tier
    volumes:
      - /home/mike/workspace/git/airflow_poc/airflow_poc/db:/bitnami/postgresql
      - /home/mike/workspace/git/airflow_poc/airflow_poc/db/conf/:/bitnami/postgresql/conf/
